### Получить книгу по id (id указан после /)
GET http://localhost:8080/books/2

### Получить список всех книг
GET http://localhost:8080/books/

### Обновить книгу по id (id указан после /)
PUT http://localhost:8080/books/4
Content-Type: application/json

{
  "id": 4,
  "bookName": "Бесконечная земля",
  "authors": [
    {
      "id": 4,
      "authorName": "Терри Пратчетт"
    },
    {
      "id": 6,
      "authorName": "Стивен Бакстер"
    }
  ],
  "genres": [
    {
      "id": 1,
      "genreName": "Фэнтези"
    },
    {
      "id": 3,
      "genreName": "Научная фантастика"
    },
    {
      "id": 5,
      "genreName": "Роман"
    }
  ]
}

### Создать новую книгу
POST http://localhost:8080/books/
Content-Type: application/json

{
  "id": 64,
  "bookName": "Одноэтажная Америка",
  "authors": [
    {
      "id": 7,
      "authorName": "Илья Ильф"
    },
    {
      "id": 8,
      "authorName": "Евгений Петров"
    }
  ],
  "genres": [
    {
      "id": 6,
      "genreName": "Юмор"
    }
  ]
}

### Удалить книгу по id (id указан после /)
DELETE http://localhost:8080/books/2

### Получить список всех книг от автора (автор указан после ?authorName=)
GET http://localhost:8080/books?authorName=row

### Получить книги по id автора (id указан после /by-author/)
GET http://localhost:8080/books/by-author/4

### Получить книги по id жанра (id указан после /genre/)
GET http://localhost:8080/books/genre/1

### Получить книги, у которых средний рейтинг строго больше avgRating (avgRating указан после /avg-rating/)
GET http://localhost:8080/books/avg-rating/4.1

### Получить книги, у которых средний рейтинг строго больше avgRating и жанр равен id (avgRating указан после /avg-rating/, genreId указан после ?genreId)
GET http://localhost:8080/books/avg-rating/4.1?genreId=1

### Получить отзыв по id книги (id указан после /book/)
GET http://localhost:8080/reviews/book/1

### Получить все отзыва от ревьювера (имя указано после ?reviewerName=)
GET http://localhost:8080/reviews?reviewerName=Sergei

### Обновить отзыв по id (id указан после /)
PUT http://localhost:8080/reviews/3
Content-Type: application/json

{
  "id": 3,
  "bookId": 1,
  "rating": 5,
  "reviewerName": "Sergei",
  "reviewText": "Я перечитал книгу с ребенком. Неплохо."
}

### Создать новый отзыв
POST http://localhost:8080/reviews/
Content-Type: application/json

{
  "id": 5342,
  "bookId": 3,
  "rating": 10,
  "reviewerName": "Irina",
  "reviewText": "Очень залипательно, я обожаю этот мир!"
}

### Удалить отзыв по id (id указан после /)
DELETE http://localhost:8080/reviews/3

### Получить автора по id (id указан после /)
GET http://localhost:8080/authors/2

### Обновить автора по id (id указан после /)
PUT http://localhost:8080/authors/4
Content-Type: application/json

{
  "id": 4,
  "authorName": "Terry Pratchett"
}

### Создать нового автора
POST http://localhost:8080/authors/
Content-Type: application/json

{
  "id": 5342,
  "authorName": "Leo Tolstoy"
}

### Удалить автора по id (id указан после /)
DELETE http://localhost:8080/authors/2

### Получить жанр по id (id указан после /)
GET http://localhost:8080/genres/2

### Получить все жанры
GET http://localhost:8080/genres/

### Обновить жанр по id (id указан после /)
PUT http://localhost:8080/genres/1
Content-Type: application/json

{
  "id": 1,
  "genreName": "Фэнтези"
}

### Создать новый жанр
POST http://localhost:8080/genres/
Content-Type: application/json

{
  "id": 5342,
  "genreName": "Ужасы"
}

### Удалить жанр по id (id указан после /)
DELETE http://localhost:8080/genres/8