DELETE FROM book_authors;
DELETE FROM book_reviews;
DELETE FROM books;
DELETE FROM authors;

ALTER SEQUENCE books_seq RESTART WITH 1;
ALTER SEQUENCE authors_seq RESTART WITH 1;
ALTER SEQUENCE book_reviews_seq RESTART WITH 1;